import './globals.css'
import { Inter } from 'next/font/google'

import { ClerkProvider } from '@clerk/nextjs'
import { ptBR } from '@clerk/localizations'
import { neobrutalism } from '@clerk/themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      localization={ptBR}
      appearance={{
        baseTheme: neobrutalism,
        elements: {
          logoImage: 'rounded-full border-2 border-violet-400',
          logoBox:
            'flex justify-center rounded-full border-2 border-violet-400 w-16 h-16 p-1 bg-violet-300 ',
          formButtonPrimary: 'bg-violet-500 hover:bg-violet-600',
          footerActionLink: 'text-violet-500 hover:text-violet-600',
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <div className="h-screen flex justify-center items-center bg-violet-500">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
